Repository Team-Do-Nothing/swithme-frontend, pull requests merged in 2023-11, with the labels that each got.

#39 Feature/auth
  package-lock.json
  package.json
  public/team_do_nothing.png
  src/app/(auth)/mypage/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signin/social/api/route.ts
  src/app/(auth)/signin/social/kakao/api/route.ts
  src/app/(auth)/signin/social/kakao/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/signup/social/kakao/[oauthId]/page.tsx
  src/redux/interface.ts
  src/redux/slices/authSlice.ts
  src/redux/store.ts
  tailwind.config.ts
Labels: epic

#53 [내 스터디] 게시판 페이지 구현
  src/app/mygroup/[id]/board/[boardId]/page.tsx
  src/app/mygroup/[id]/board/page.tsx
  src/app/mygroup/[id]/notice/page.tsx
Labels: epic

#64 [스터디 검색] 검색 및 카드 컴포넌트 디자인 수정
  src/app/groups/page.tsx
  src/app/layout.tsx
  src/components/Card.tsx
  src/components/CardFilter.tsx
  src/components/CardSearch.tsx
Labels: style

#69 [fix] 스터디 목록 카드 검색 컴포넌트 호버 스타일 수정 및 카드 컴포넌트 데이터 오류 수정
  src/components/Card.tsx
  src/components/CardSearch.tsx
Labels: fix

#73 [fix] 공지사항 게시글 및 게시판 게시글 페이지 변경
  src/app/mygroup/[id]/board/[boardId]/page.tsx
  src/app/mygroup/[id]/notice/[noticeId]/page.tsx
Labels: fix
